server:
   port: 8099
   
#Conextion to Mongo DB
spring:
  application:
    name: credit-payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/PAYMENT
#      uri: mongodb://admin:password@mongodb-service:27017/PAYMENT
         
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposre:
        include: "*"