server:
   port: 8085

spring:
  cloud:
    gateway:
      routes:
      - id: customer_service
        uri: http://localhost:8090/
        predicates:
        - Path=/customer-service/**
      - id: transaction_service
        uri: http://localhost:8092/
        predicates:
        - Path=/transaction-service/** 
      - id: product_service
        uri: http://localhost:8093/
        predicates:
        - Path=/product-service/**
      - id: purchase_service
        uri: http://localhost:8094/
        predicates:
        - Path=/purchase-service/**  
         
       
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
        