server:
   port: 8085

spring:
  cloud:
    gateway:
      routes:
      - id: customer_service
        uri: http://localhost:8090/
        predicates:
        - Path=/customer/**
      - id: transaction_service
        uri: http://localhost:8092/
        predicates:
        - Path=/transaction/** 
      - id: product_service
        uri: http://localhost:8093/
        predicates:
        - Path=/product/**
      - id: purchase_service
        uri: http://localhost:8094/
        predicates:
        - Path=/purchase/**
      - id: account_service
        uri: http://localhost:8095/
        predicates:
        - Path=/account/** 
      - id: withdrawal_service
        uri: http://localhost:8096/
        predicates:
        - Path=/withdrawal/**  
      - id: deposit_service
        uri: http://localhost:8097/
        predicates:
        - Path=/deposit/** 
      - id: credit-consumer-service
        uri: http://localhost:8098/
        predicates:
        - Path=/credit/**
      - id: credit-payment-service
        uri: http://localhost:8099/
        predicates:
        - Path=/payment/**        
         
       
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
        