server:
   port: 8085

spring:
  cloud:
    gateway:
      routes:
      - id: customer_service
        uri: http://localhost:8090/
        predicates:
        - Path=/customer/**
#        filters:
#        - name: CircuitBreaker
#          args:
#              name: ms-customer
#              fallbackuri: forward:/customerServiceFallBack
      - id: transaction_service
        uri: http://localhost:8092/
        predicates:
        - Path=/transaction/** 
      - id: product_service
        uri: http://localhost:8093/
        predicates:
        - Path=/product/**
        
hystrix:
    command:
        fallbackcmd:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000         
       
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
        